const item2: string = "coin pouch";
const item3: string = "~~bota bag~~ stylized water bottle";
const item4: string = "tarot card deck";
const item5: string = "leather satchel";
const item6: string = "Handmade lyre";

export const badges = [
  {
    'title': 'Fairgoer',
    'notes': '$65 until 2/28, $70 until 8/27, $75 until 8/30 (door price)',
    'price': '$70',
    'perks': [
      'Fairgoer badge',
      'Admission to the convention for all three days',
      'Simple colored lanyard',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': false,
    'imagePecentage': 40,
  },
  {
    'title': 'Mare Supporter',
    'notes': 'Available until 6/21',
    'price': '$180',
    'perks': [
      'Mare Supporter badge',
      'Admission to the convention for all three days',
      'Sponsor lanyard',
      'Thanks on website (optional)',
      `Commemorative sponsor gifts, including ${item2}, patch, and soap`,
      'Signed print from your favorite mascot',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 40,
  },
{
    'title': 'Mare Latecoomer',
    'notes': 'Available from 6/22 until 8/27',
    'price': '$125',
    'perks': [
      'Mare Supporter badge',
      'Admission to the convention for all three days',
      'Sponsor lanyard',
      'Thanks on website (optional)',
      '$20 of con store coupons',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': false,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Enjoyer',
    'notes': 'available until 6/21',
    'price': '$400',
    'perks': [
      '**All Mare Supporter perks (except badge)**',
      'Mare Enjoyer badge',
      'Early access to Vendor Stalls, AD Vendor Stalls, Con Store, and Mare Stage events',
      'Priority badge pickup',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Appreciator',
    'notes': 'available until 6/21',
    'price': '$625',
    'perks': [
      '**All Mare Enjoyer perks (except badge and mascot print)**',
      'Mare Appreciator badge',
      `Commemorative upper tier sponsor gifts, including ${item3}, ${item4}, and ${item5}`,
      'Special edition con book',
      'Signed prints from all the mascots'
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Enthusiast',
    'notes': 'Available until 6/21 (limited to 90)',
    'price': '$1,300',
    'perks': [
      '**All Mare Appreciator perks (except badge)**',
      'Mare Enthusiast badge',
      'Your choice of a king or double queen hotel room for 4 nights (check-in on Thursday, check-out on Monday); [nights can be added](/roomchanges) at con rate ($119 plus taxes and fees, contact [attendees@marefair.org](mailto:attendees@marefair.org))',
      'One free breakfast buffet voucher at Covington Mills in the hotel'
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Admirer',
    'notes': 'Available until 6/21 (limited to 30)',
    'price': '$1,700',
    'perks': [
      '**All Mare Enthusiast perks (except badge)**',
      'Mare Admirer badge',
      'Phone number for the Head Pony In Charge (call him when you have any issues or are just feeling lonely)',
      'Free ticket to Cinemare Night on Thursday (includes transportation)',
      'Reserved seat at Mare Stage events (based on availability)',
      'Thanks at the opening and closing ceremonies (optional)'
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Connoisseur',
    'notes': 'Available until 6/21 (limited to 5)',
    'price': '$2,300',
    'perks': [
      '**All Mare Admirer perks (except badge)**',
      'Mare Connoisseur badge',
      'An extra two breakfast buffet vouchers at Covington Mills in the hotel (total of three)',
      'Free digital pony art commission (colored)',
      'Free ticket to the Spaghetti and Tendie dinner',
      'Free ticket to Maredival Times event on Monday (includes transportation)',
      'Online voice conversation with the Ponies In Charge before or after the con',
      'Personalized voice message from mascot(s) of your choice',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Aficionado',
    'notes': 'Available until 6/21 (limited to 4)',
    'price': '$3,900',
    'perks': [
      '**All Mare Connoisseur perks (except badge, hotel room, and art commission)**',
      'Mare Aficionado badge with custom art',
      '~~Junior~~ One Bedroom Suite for 4 nights (check-in on Thursday, check-out on Monday); [nights can be added](/roomchanges) at con rate ($119 plus taxes and fees, may be limited based on availability, contact [attendees@marefair.org](mailto:attendees@marefair.org))',
      'Free digital pony art commission (shaded with background)',
      'Access to staff hospitality suite',
      'Access to con store on Thursday',
      item6,
      'Invitation to come on stage to speak briefly during the opening and closing ceremonies (optional)',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Fanatic',
    'notes': 'Available until 6/21 (limited to 2)',
    'price': '$5,555',
    'perks': [
      '**All Mare Aficionado perks (except badge)**',
      'Mare Fanatic badge with custom art',
      'An extra six breakfast buffet vouchers at Covington Mills in the hotel (total of nine, enough for you plus two friends for three breakfasts)',
      'Limo ride to/from airport or other location within reasonable distance',
      'Two free Mare Supporter badges for your frens (must be redeemed before 6/21)',
      'Two free tickets to Cinemare Night on Thursday (includes transportation, total of 3, enough for you plus two friends)',
      'Front-of-line privilege to all lines (you can cut to front of line)',
      'Access to vendor stalls on Thursday evening (vendors may not be set up yet and may not be able to sell anything, no guarantees on anything)'
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Mare Schizo',
    'notes': 'Available until 6/21 (limited to 1)',
    'price': '$15,555',
    'perks': [
      '**All Mare Fanatic perks (except badge, One Bedroom Suite, and Mare Supporter badges)**',
      'Mare Schizo badge with custom art',
      'Backstage pass (may require a staff escort when in areas restricted to convention staff)',
      'Up to five Mare Appreciator badges for your frens (must be redeemed before 6/21)',
      'Up to six tickets for up to three days at Disney World, Universal, and/or SeaWorld/Busch Gardens theme parks (ask for details)',
      '~~Junior~~ One Bedroom Suite for 7 nights (check-in after 8/23, check-out before 9/4); [nights can be added](/roomchanges) at con rate ($119 plus taxes and fees, may be limited based on availability, contact [attendees@marefair.org](mailto:attendees@marefair.org))',
      'Your choice of a king or double queen hotel room for 7 nights for your frens (check-in after 8/23, check-out before 9/4); [nights can be added](/roomchanges) at con rate ($119 plus taxes and fees, contact [attendees@marefair.org](mailto:attendees@marefair.org))',
      'Three free tickets to Cinemare Night on Thursday (includes transportation, total of six, enough for you plus five friends)',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 0,
  },
  {
    'title': 'Spirit Fairgoer',
    'notes': 'Available until 8/27',
    'price': '$45',
    'perks': [
      'Fairgoer badge',
      'Simple colored lanyard'
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': false,
    'imagePecentage': 40,
  },
  {
    'title': 'Spirit Supporter',
    'notes': 'Available until 6/21',
    'price': '$150',
    'perks': [
      'Mare Supporter badge',
      'Sponsor lanyard',
      'Thanks on website (optional)',
      `Commemorative sponsor gifts, including ${item2}, patch, and soap`,
      'Signed print from your favorite mascot',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 20,
  },
  {
    'title': 'Spirit Latecoomer',
    'notes': 'Available from 6/21 until 8/27',
    'price': '$135',
    'perks': [
      'Mare Supporter badge',
      'Sponsor lanyard',
      'Thanks on website (optional)',
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': false,
    'imagePecentage': 10,
  },
  {
    'title': 'Spirit Appreciator',
    'notes': 'Available until 6/21',
    'price': '$550',
    'perks': [
      '**All Spirit Supporter perks (except badge and mascot print)**',
      'Mare Appreciator badge',
      `Commemorative upper tier sponsor gifts, including ${item3}, ${item4}, and ${item5}`,
      'Special edition con book',
      'Signed prints from all the mascots'
    ],
    'link': 'https://reg.marefair.org/',
    'soldOut': true,
    'imagePecentage': 20,
  },
]
